[package]
name = "closures_iterators"
version = "0.1.0"
edition = "2021"
# homepage = "https://github.com/Jack0fClubs/rust_two"
# repository = "https://github.com/Jack0fClubs/rust_two"
# readme = "README.md"
# keywords = "paractice"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
